AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/20160613165812_devise_create_users.rb'
    - 'bin/*'

# "Favor format over String#%."
Style/FormatString:
  Enabled: false

# Freeze mutable objects assigned to constants.
Style/MutableConstant:
  Enabled: false

# Use NN.zero? instead of NN == 0
Style/NumericPredicate:
  Enabled: false

# When using method_missing, define respond_to_missing?.
Style/MethodMissing:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 140

# rubocop's AbcSize is ridiculously low.
Metrics/AbcSize:
  Max: 30

# Cop supports --auto-correct.
Style/TrivialAccessors:
  Enabled: false

# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'spec/lib/markdown_spec.rb'

# Otherwise we'll end up with tons of bogus documentation.
Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'Gemfile'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/ModuleFunction:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb'

# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'config.ru'
    - 'config/**/*.rb'

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# The Style/GuardClause cop tends to produce false positives in SimpleCov
Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Prefer !expression.nil? over expression != nil. WAT?
Style/NonNilCheck:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Performance/StartWith:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
