defaults: &defaults
  adapter:    postgresql
  host:       '127.0.0.1'
  port:       '5432'
  encoding:   utf8
  pool:       5
  database:   'postqueue'

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
  database:   'postqueue_test'
