development:
  adapter:  postgresql
  host:     localhost
  port:     5432
  database: postqueue
  username: postqueue
  password: postqueue
test:
  adapter:  postgresql
  host:     localhost
  port:     5432
  database: postqueue_test
  username: postqueue
  password: postqueue
