# GH actions file for Ruby testing

name: Ruby Build
on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    services:
      # Docker services, use images from Docker hub
      # Using dockers health-check to wait for services to start,
      # see https://ryaneschinger.com/blog/using-docker-native-health-checks/
      postgres:
        image: postgres:9.6.11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 2s
          --health-retries 15
    steps:
      - name: Checkout code from git
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Rubocop linting
        run: bundle exec rubocop --color --parallel

      - name: Prepare test DB
        run: scripts/prepare_pg

      - name: Run RSpec unit tests
        run: bundle exec rspec --force-color
